#!/bin/sh
# curl -X GET "http://localhost:5601/api/features" -H 'kbn-xsrf: true'
#-H 'Content-Type: application/json' -d' { "type": "index-pattern" } '
 curl -X POST "http://localhost:5601/api/saved_objects/_export" \
      -H 'kbn-xsrf: true' \
      -H 'Content-Type: application/json' \
      -d' { "type": "index-pattern" } '
