#!/bin/sh
# Kibana installation dir for Ubuntu/Debian
KIBANA_HOME=/usr/share/kibana

# Check Node version for your Kibana
# In my case >>  "node": "10.15.2"
cat $KIBANA_HOME/package.json | grep node

# Install Node.js with package manager
curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
sudo apt-get install -y nodejs

# Check installed Node version
# In my case >> v10.16.3 (!! VERSION MISMATCH !!)
node --version

# Install Node version manager 'n'
# (Technically, you can install 'n' without npm since it's just a shell script.
#  It might be simpler to install it without npm. In that case, you need to 
#  uninstall all node and npm before running installation script.)
sudo npm install -g n

# Install Node version matching with Kibana
sudo n install 10.15.2

# Uninstall Ubuntu/Debian Node. 'node_modules' will be kept so you can still use 'n'.
# This is to make sure Node installed by 'n' is found first in the PATH.
sudo apt purge -y nodejs

# Check Node version. It should be 'v10.15.2'
which node
which npm
node --version

# Install bower for Kibana time-plugin
sudo npm install -g bower

# Install plugin
cd $KIBANA_HOME/plugins
sudo git clone http://github.com/nreese/kibana-time-plugin.git
cd kibana-time-plugin
sudo git checkout master

# Update plugin package.json to specify your Kibana version.
sudo sed -i -e 's/"version".*/"version" : "7.3.2"/' package.json

# --allow-root was required to run Bower as root
sudo bower install --allow-root

# Restart Kibana
sudo systemctl restart kibana

