#!/bin/sh

# Kibana installation dir for Ubuntu/Debian
KIBANA_HOME=/usr/share/kibana

# Check Node version
ls $KIBANA_HOME
exit

# Install Node.js with package manager
curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
sudo apt-get install -y nodejs

# NPN
sudo npm install -g bower

# Debian plugin dir
cd /usr/share/kibana/plugins
sudo git clone http://github.com/nreese/kibana-time-plugin.git
cd kibana-time-plugin
sudo git checkout master
sudo sed -i -e 's/"version".*/"version" : "7.3.2"/' package.json
sudo bower install --allow-root

